"""
run_logger.py — Structured JSON Run Snapshot Logger.
Persists complete agent execution traces (queries, DPFH contexts, tool calls,
state transitions, latencies, and responses) to disk for observability and eval fixtures.
"""
# json: Standard library for serializing run dictionaries into human-readable formatted JSON
import json
# uuid: Generates unique 128-bit identifiers to prevent run snapshot collisions
import uuid
# datetime & timezone: Generates standardized ISO-8601 UTC timestamps for chronological indexing
from datetime import datetime, timezone
# Path: Object-oriented filesystem path manipulation
from pathlib import Path
from typing import Any, Optional

# Root logs directory located at the project workspace root
RUNS_DIR = Path(__file__).resolve().parent.parent.parent.parent / "logs" / "runs"


def _ensure_runs_dir() -> Path:
    """
    Ensures the target logs/runs directory exists on disk.
    Creates parent directories recursively if missing.
    """
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    return RUNS_DIR


def log_run(
    agent_name: str,
    query: str,
    response: str,
    thread_id: Optional[str] = None,
    domain: Optional[str] = None,
    confidence: Optional[float] = None,
    reasoning: Optional[str] = None,
    dpfh_injected_files: Optional[list[str]] = None,
    tool_calls: Optional[list[dict[str, Any]]] = None,
    trace_events: Optional[list[dict[str, Any]]] = None,
    latency_seconds: Optional[float] = None,
    metadata: Optional[dict[str, Any]] = None,
) -> Path:
    """
    Serializes an agent execution run snapshot to a formatted JSON file in logs/runs/.

    Args:
        agent_name: Identifier of the executing agent (e.g., 'career', 'librarian', 'router')
        query: Raw input prompt / content provided by the user or caller
        response: Final markdown text response generated by the agent
        thread_id: UI conversation UUID or LangGraph checkpointer thread ID
        domain: Domain classification assigned by the Router (if applicable)
        confidence: Router classification confidence score (0.0 to 1.0)
        reasoning: Text justification for the domain routing decision
        dpfh_injected_files: List of file paths deterministically hydrated into context
        tool_calls: List of tool calls executed during the run [{name: str, args: dict}]
        trace_events: Full array of SSE / AgentTracer telemetry events
        latency_seconds: Wall-clock execution time in seconds
        metadata: Arbitrary dictionary for model names, token counts, or flags

    Returns:
        Path to the persisted JSON run snapshot file
    """
    runs_dir = _ensure_runs_dir()
    
    # Generate unique 8-character suffix and ISO timestamp
    run_id = str(uuid.uuid4())[:8]
    now_utc = datetime.now(timezone.utc)
    timestamp_iso = now_utc.isoformat()
    timestamp_compact = now_utc.strftime("%Y%m%dT%H%M%SZ")
    
    # Construct filename: YYYYMMDDTHHMMSSZ_<agent>_<short_id>.json
    safe_agent = agent_name.replace(" ", "_").lower()
    filename = f"{timestamp_compact}_{safe_agent}_{run_id}.json"
    file_path = runs_dir / filename

    # Build structured snapshot payload
    snapshot = {
        "run_id": run_id,
        "timestamp": timestamp_iso,
        "thread_id": thread_id or "unspecified",
        "agent_name": agent_name,
        "domain": domain,
        "confidence": confidence,
        "reasoning": reasoning,
        "input_query": query,
        "output_response": response,
        "latency_seconds": round(latency_seconds, 3) if latency_seconds is not None else None,
        "dpfh_injected_files": dpfh_injected_files or [],
        "tool_calls": tool_calls or [],
        "trace_events_count": len(trace_events) if trace_events else 0,
        "trace_events": trace_events or [],
        "metadata": metadata or {},
    }

    # Write formatted, indented JSON with UTF-8 encoding
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(snapshot, f, indent=2, ensure_ascii=False)

    return file_path


def list_runs(limit: int = 20, agent: Optional[str] = None) -> list[dict[str, Any]]:
    """
    Lists recent run snapshots ordered from newest to oldest.

    Args:
        limit: Maximum number of run metadata entries to return
        agent: Optional agent name filter (e.g., 'career')

    Returns:
        List of lightweight run summary dictionaries
    """
    runs_dir = _ensure_runs_dir()
    json_files = sorted(runs_dir.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
    
    summaries = []
    for p in json_files:
        if len(summaries) >= limit:
            break
        try:
            with open(p, "r", encoding="utf-8") as f:
                data = json.load(f)
            
            # Apply agent filter if specified
            if agent and data.get("agent_name", "").lower() != agent.lower():
                continue
                
            summaries.append({
                "run_id": data.get("run_id"),
                "filename": p.name,
                "timestamp": data.get("timestamp"),
                "thread_id": data.get("thread_id"),
                "agent_name": data.get("agent_name"),
                "domain": data.get("domain"),
                "query_preview": data.get("input_query", "")[:100],
                "response_preview": data.get("output_response", "")[:100],
                "latency_seconds": data.get("latency_seconds"),
                "tool_calls_count": len(data.get("tool_calls", [])),
            })
        except Exception:
            continue

    return summaries


def get_run(run_id: str) -> Optional[dict[str, Any]]:
    """
    Retrieves full run snapshot dictionary by run_id or matching filename.

    Args:
        run_id: Unique 8-character ID or full JSON filename

    Returns:
        Full JSON dictionary of the run snapshot, or None if not found
    """
    runs_dir = _ensure_runs_dir()
    
    # Check direct filename match
    direct_path = runs_dir / run_id
    if direct_path.is_file() and direct_path.suffix == ".json":
        with open(direct_path, "r", encoding="utf-8") as f:
            return json.load(f)
            
    # Search by run_id in filename or contents
    for p in runs_dir.glob("*.json"):
        if run_id in p.name:
            with open(p, "r", encoding="utf-8") as f:
                return json.load(f)
                
    return None


def get_latest_run() -> Optional[dict[str, Any]]:
    """
    Retrieves the most recent run snapshot from disk.

    Returns:
        Full JSON dictionary of the latest run, or None if no runs exist
    """
    runs_dir = _ensure_runs_dir()
    json_files = sorted(runs_dir.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not json_files:
        return None
    with open(json_files[0], "r", encoding="utf-8") as f:
        return json.load(f)
